control 'AU-06(05)' do
  impact 0.5
  title "analysis of audit records is integrated with analysis of #{input('au_06_05_odp_01')} to further enhance the ability to identify inappropriate or unusual activity."
  desc <<~DESC
    Integrate analysis of audit records with analysis of #{input('au_06_05_odp_01')} to further enhance the ability to identify inappropriate or unusual activity.
  DESC
  desc 'check', <<~CHECK
    Determine if:
      analysis of audit records is integrated with analysis of #{input('au_06_05_odp_01')} to further enhance the ability to identify inappropriate or unusual activity.

    Assessment methods and objects:
      EXAMINE: Audit and accountability policy; system security plan; privacy plan; procedures addressing audit review, analysis, and reporting; system design documentation; system configuration settings and associated documentation; integrated analysis of audit records, vulnerability scanning information, performance data, network monitoring information, and associated documentation; other relevant documents or records
      INTERVIEW: Organizational personnel with audit review, analysis, and reporting responsibilities; organizational personnel with information security and privacy responsibilities
      TEST: Mechanisms implementing the capability to integrate analysis of audit records with analysis of data/information sources
  CHECK
  desc 'fix', <<~FIX
    NIST SP 800-53 Rev 5 and SP 800-53A Rev 5 publish no remediation text for this control. Implement the control statement above, record the implementation statement in the SSP, and replace this text with the system-specific remediation once the control is automated.
  FIX
  desc 'guidance', <<~GUIDANCE
    Integrated analysis of audit records does not require vulnerability scanning, the generation of performance data, or system monitoring. Rather, integrated analysis requires that the analysis of information generated by scanning, monitoring, or other data collection activities is integrated with the analysis of audit record information. Security Information and Event Management tools can facilitate audit record aggregation or consolidation from multiple system components as well as audit record correlation and analysis. The use of standardized audit record analysis scripts developed by organizations (with localized script adjustments, as necessary) provides more cost-effective approaches for analyzing audit record information collected. The correlation of audit record information with vulnerability scanning information is important in determining the veracity of vulnerability scans of the system and in correlating attack detection events with scanning results. Correlation with performance data can uncover denial-of-service attacks or other types of attacks that result in the unauthorized use of resources. Correlation with system monitoring information can assist in uncovering attacks and in better relating audit information to operational situations.
  GUIDANCE
  tag nist: ['AU-6 (5)']
  tag control: 'AU-6 (5)'
  tag objective: 'AU-06(05)'
  tag rev: 'Rev_5'
  tag family: 'Audit and Accountability'
  tag baseline: %w{HIGH}
  tag baseline_high: true
  tag control_au_6_5: true
  tag odp: %w{au_06_05_odp_01}

  describe 'NIST SP 800-53A Rev 5 objective AU-06(05)' do
    skip 'Not automated. This control is a skeleton: it carries the NIST control language and the SP 800-53A assessment procedure but performs no check. Replace this stub with InSpec resource tests to automate it, or assess it manually and record the result as an attestation.'
  end
end
