control 'AU-11(01)' do
  impact 0.5
  title "#{input('au_11_01_odp')} are employed to ensure that long-term audit records generated by the system can be retrieved."
  desc <<~DESC
    Employ #{input('au_11_01_odp')} to ensure that long-term audit records generated by the system can be retrieved.
  DESC
  desc 'check', <<~CHECK
    Determine if:
      #{input('au_11_01_odp')} are employed to ensure that long-term audit records generated by the system can be retrieved.

    Assessment methods and objects:
      EXAMINE: Audit and accountability policy; system security plan; privacy plan; audit record retention policy and procedures; system design documentation; system configuration settings and associated documentation; audit record archives; audit logs; audit records; other relevant documents or records
      INTERVIEW: Organizational personnel with audit record retention responsibilities; organizational personnel with information security and privacy responsibilities; system/network administrators
      TEST: Mechanisms implementing audit record retention capability
  CHECK
  desc 'fix', <<~FIX
    NIST SP 800-53 Rev 5 and SP 800-53A Rev 5 publish no remediation text for this control. Implement the control statement above, record the implementation statement in the SSP, and replace this text with the system-specific remediation once the control is automated.
  FIX
  desc 'guidance', <<~GUIDANCE
    Organizations need to access and read audit records requiring long-term storage (on the order of years). Measures employed to help facilitate the retrieval of audit records include converting records to newer formats, retaining equipment capable of reading the records, and retaining the necessary documentation to help personnel understand how to interpret the records.
  GUIDANCE
  tag nist: ['AU-11 (1)']
  tag control: 'AU-11 (1)'
  tag objective: 'AU-11(01)'
  tag rev: 'Rev_5'
  tag family: 'Audit and Accountability'
  tag baseline: %w{}
  tag control_au_11_1: true
  tag odp: %w{au_11_01_odp}

  describe 'NIST SP 800-53A Rev 5 objective AU-11(01)' do
    skip 'Not automated. This control is a skeleton: it carries the NIST control language and the SP 800-53A assessment procedure but performs no check. Replace this stub with InSpec resource tests to automate it, or assess it manually and record the result as an attestation.'
  end
end
