control 'SI-04(12)' do
  impact 0.5
  title "#{input('si_04_12_odp_01')} is/are alerted using #{input('si_04_12_odp_02')} when #{input('si_04_12_odp_03')} indicate inappropriate or unusual activities with security or privacy implications."
  desc <<~DESC
    Alert #{input('si_04_12_odp_01')} using #{input('si_04_12_odp_02')} when the following indications of inappropriate or unusual activities with security or privacy implications occur: #{input('si_04_12_odp_03')}.
  DESC
  desc 'check', <<~CHECK
    Determine if:
      #{input('si_04_12_odp_01')} is/are alerted using #{input('si_04_12_odp_02')} when #{input('si_04_12_odp_03')} indicate inappropriate or unusual activities with security or privacy implications.

    Assessment methods and objects:
      EXAMINE: System and information integrity policy; system and information integrity procedures; procedures addressing system monitoring tools and techniques; system design documentation; system monitoring tools and techniques documentation; system configuration settings and associated documentation; list of inappropriate or unusual activities with security and privacy implications that trigger alerts; suspicious activity reports; alerts provided to security and privacy personnel; system monitoring logs or records; system audit records; system security plan; privacy plan; other relevant documents or records
      INTERVIEW: System/network administrators; organizational personnel with information security and privacy responsibilities; system developers; organizational personnel installing, configuring, and/or maintaining the system; organizational personnel responsible for monitoring the system; organizational personnel responsible for the intrusion detection system
      TEST: Organizational processes for intrusion detection and system monitoring; automated mechanisms supporting and/or implementing intrusion detection and system monitoring capabilities; automated mechanisms supporting and/or implementing automated alerts to security personnel
  CHECK
  desc 'fix', <<~FIX
    NIST SP 800-53 Rev 5 and SP 800-53A Rev 5 publish no remediation text for this control. Implement the control statement above, record the implementation statement in the SSP, and replace this text with the system-specific remediation once the control is automated.
  FIX
  desc 'guidance', <<~GUIDANCE
    Organizational personnel on the system alert notification list include system administrators, mission or business owners, system owners, senior agency information security officer, senior agency official for privacy, system security officers, or privacy officers. Automated organization-generated alerts are the security alerts generated by organizations and transmitted using automated means. The sources for organization-generated alerts are focused on other entities such as suspicious activity reports and reports on potential insider threats. In contrast to alerts generated by the organization, alerts generated by the system in [SI-4(5)](#si-4.5) focus on information sources that are internal to the systems, such as audit records.
  GUIDANCE
  tag nist: ['SI-4 (12)']
  tag control: 'SI-4 (12)'
  tag objective: 'SI-04(12)'
  tag rev: 'Rev_5'
  tag family: 'System and Information Integrity'
  tag baseline: %w{HIGH}
  tag baseline_high: true
  tag control_si_4_12: true
  tag odp: %w{si_04_12_odp_01 si_04_12_odp_02 si_04_12_odp_03}

  describe 'NIST SP 800-53A Rev 5 objective SI-04(12)' do
    skip 'Not automated. This control is a skeleton: it carries the NIST control language and the SP 800-53A assessment procedure but performs no check. Replace this stub with InSpec resource tests to automate it, or assess it manually and record the result as an attestation.'
  end
end
