control 'AU-13' do
  impact 0.5
  title 'Monitoring for Information Disclosure'
  desc <<~DESC
    a. Monitor #{input('au_13_odp_01')} #{input('au_13_odp_02')} for evidence of unauthorized disclosure of organizational information; and
    b. If an information disclosure is discovered:
      1. Notify #{input('au_13_odp_03')} ; and
      2. Take the following additional actions: #{input('au_13_odp_04')}.
  DESC
  desc 'check', <<~CHECK
    Determine if:
      AU-13a. #{input('au_13_odp_01')} is/are monitored #{input('au_13_odp_02')} for evidence of unauthorized disclosure of organizational information;
      AU-13b.
        AU-13b.01 #{input('au_13_odp_03')} are notified if an information disclosure is discovered;
        AU-13b.02 #{input('au_13_odp_04')} are taken if an information disclosure is discovered.

    Assessment methods and objects:
      EXAMINE: Audit and accountability policy; system security plan; privacy plan; procedures addressing information disclosure monitoring; system design documentation; system configuration settings and associated documentation; monitoring records; system audit records; other relevant documents or records
      INTERVIEW: Organizational personnel with responsibilities for monitoring open-source information and/or information sites; organizational personnel with security and privacy responsibilities
      TEST: Mechanisms implementing monitoring for information disclosure
  CHECK
  desc 'fix', <<~FIX
    NIST SP 800-53 Rev 5 and SP 800-53A Rev 5 publish no remediation text for this control. Implement the control statement above, record the implementation statement in the SSP, and replace this text with the system-specific remediation once the control is automated.
  FIX
  desc 'guidance', <<~GUIDANCE
    Unauthorized disclosure of information is a form of data leakage. Open-source information includes social networking sites and code-sharing platforms and repositories. Examples of organizational information include personally identifiable information retained by the organization or proprietary information generated by the organization.
  GUIDANCE
  tag nist: ['AU-13']
  tag rev: 'Rev_5'
  tag family: 'Audit and Accountability'
  tag baseline: %w{}
  tag odp: %w{au_13_odp_01 au_13_odp_02 au_13_odp_03 au_13_odp_04}

  describe 'NIST SP 800-53 Rev 5 control AU-13' do
    skip 'Not automated. This control is a skeleton: it carries the NIST control language and the SP 800-53A assessment procedure but performs no check. Replace this stub with InSpec resource tests to automate it, or assess it manually and record the result as an attestation.'
  end
end
