control 'IA-5 (18)' do
  impact 0.5
  title 'Password Managers'
  desc <<~DESC
    (a) Employ #{input('ia_05_18_odp_01')} to generate and manage passwords; and
    (b) Protect the passwords using #{input('ia_05_18_odp_02')}.
  DESC
  desc 'check', <<~CHECK
    Determine if:
      IA-05(18)(a) #{input('ia_05_18_odp_01')} are employed to generate and manage passwords;
      IA-05(18)(b) the passwords are protected using #{input('ia_05_18_odp_02')}.

    Assessment methods and objects:
      EXAMINE: Identification and authentication policy; procedures addressing identifier management; system security plan; system design documentation; mechanisms providing dynamic binding of identifiers and authenticators; system configuration settings and associated documentation; system audit records; other relevant documents or records
      INTERVIEW: Organizational personnel with identification and authentication management responsibilities; organizational personnel with information security responsibilities; system/network administrators
      TEST: Mechanisms supporting and/or implementing account management capability; mechanisms supporting and/or implementing identification and authentication management capabilities for the system
  CHECK
  desc 'fix', <<~FIX
    NIST SP 800-53 Rev 5 and SP 800-53A Rev 5 publish no remediation text for this control. Implement the control statement above, record the implementation statement in the SSP, and replace this text with the system-specific remediation once the control is automated.
  FIX
  desc 'guidance', <<~GUIDANCE
    For systems where static passwords are employed, it is often a challenge to ensure that the passwords are suitably complex and that the same passwords are not employed on multiple systems. A password manager is a solution to this problem as it automatically generates and stores strong and different passwords for various accounts. A potential risk of using password managers is that adversaries can target the collection of passwords generated by the password manager. Therefore, the collection of passwords requires protection including encrypting the passwords (see [IA-5(1)(d)](#ia-5.1_smt.d) ) and storing the collection offline in a token.
  GUIDANCE
  tag nist: ['IA-5 (18)']
  tag rev: 'Rev_5'
  tag family: 'Identification and Authentication'
  tag baseline: %w{}
  tag odp: %w{ia_05_18_odp_01 ia_05_18_odp_02}

  describe 'NIST SP 800-53 Rev 5 control IA-5 (18)' do
    skip 'Not automated. This control is a skeleton: it carries the NIST control language and the SP 800-53A assessment procedure but performs no check. Replace this stub with InSpec resource tests to automate it, or assess it manually and record the result as an attestation.'
  end
end
