control 'RA-03(04)[02]' do
  impact 0.5
  title "#{input('ra_03_04_odp_03')} are employed to predict and identify risks to #{input('ra_03_04_odp_02')}."
  desc <<~DESC
    Employ the following advanced automation and analytics capabilities to predict and identify risks to #{input('ra_03_04_odp_02')}: #{input('ra_3_4_prm_2')}.
  DESC
  desc 'check', <<~CHECK
    Determine if:
      #{input('ra_03_04_odp_03')} are employed to predict and identify risks to #{input('ra_03_04_odp_02')}.

    Assessment methods and objects:
      EXAMINE: Risk assessment policy; security planning policy and procedures; procedures addressing organizational assessments of risk; risk assessment; risk assessment results; risk assessment reviews; risk assessment updates; risk reports; system security plan; other relevant documents or records
      INTERVIEW: Organizational personnel with risk assessment responsibilities; organizational personnel with security responsibilities
      TEST: Organizational processes for risk assessment; mechanisms supporting and/or conducting, documenting, reviewing, disseminating, and updating the risk assessment
  CHECK
  desc 'fix', <<~FIX
    NIST SP 800-53 Rev 5 and SP 800-53A Rev 5 publish no remediation text for this control. Implement the control statement above, record the implementation statement in the SSP, and replace this text with the system-specific remediation once the control is automated.
  FIX
  desc 'guidance', <<~GUIDANCE
    A properly resourced Security Operations Center (SOC) or Computer Incident Response Team (CIRT) may be overwhelmed by the volume of information generated by the proliferation of security tools and appliances unless it employs advanced automation and analytics to analyze the data. Advanced automation and analytics capabilities are typically supported by artificial intelligence concepts, including machine learning. Examples include Automated Threat Discovery and Response (which includes broad-based collection, context-based analysis, and adaptive response capabilities), automated workflow operations, and machine assisted decision tools. Note, however, that sophisticated adversaries may be able to extract information related to analytic parameters and retrain the machine learning to classify malicious activity as benign. Accordingly, machine learning is augmented by human monitoring to ensure that sophisticated adversaries are not able to conceal their activities.
  GUIDANCE
  tag nist: ['RA-3 (4)']
  tag control: 'RA-3 (4)'
  tag objective: 'RA-03(04)[02]'
  tag rev: 'Rev_5'
  tag family: 'Risk Assessment'
  tag baseline: %w{}
  tag control_ra_3_4: true
  tag odp: %w{ra_03_04_odp_02 ra_03_04_odp_03 ra_3_4_prm_2}

  describe 'NIST SP 800-53A Rev 5 objective RA-03(04)[02]' do
    skip 'Not automated. This control is a skeleton: it carries the NIST control language and the SP 800-53A assessment procedure but performs no check. Replace this stub with InSpec resource tests to automate it, or assess it manually and record the result as an attestation.'
  end
end
